// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCitrnflYufSUOCb4Ftr-IYdYPTSZ4U-e0',
    appId: '1:547289949240:web:0757f55a3ad13d3c42f2cd',
    messagingSenderId: '547289949240',
    projectId: 'restorent-pos-system',
    authDomain: 'restorent-pos-system.firebaseapp.com',
    storageBucket: 'restorent-pos-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjYfEdqcPhNstvvD0OWiJhfzoiQH1ja38',
    appId: '1:547289949240:android:303b5a29ba150d8c42f2cd',
    messagingSenderId: '547289949240',
    projectId: 'restorent-pos-system',
    storageBucket: 'restorent-pos-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2RViPmzhj2yNAqO39UFM4LpPlAfQlWMI',
    appId: '1:547289949240:ios:58fee48fc9f4655b42f2cd',
    messagingSenderId: '547289949240',
    projectId: 'restorent-pos-system',
    storageBucket: 'restorent-pos-system.firebasestorage.app',
    iosBundleId: 'com.example.restorentPosSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2RViPmzhj2yNAqO39UFM4LpPlAfQlWMI',
    appId: '1:547289949240:ios:58fee48fc9f4655b42f2cd',
    messagingSenderId: '547289949240',
    projectId: 'restorent-pos-system',
    storageBucket: 'restorent-pos-system.firebasestorage.app',
    iosBundleId: 'com.example.restorentPosSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCitrnflYufSUOCb4Ftr-IYdYPTSZ4U-e0',
    appId: '1:547289949240:web:07a90478056d982042f2cd',
    messagingSenderId: '547289949240',
    projectId: 'restorent-pos-system',
    authDomain: 'restorent-pos-system.firebaseapp.com',
    storageBucket: 'restorent-pos-system.firebasestorage.app',
  );
}
